### ISSUE TITLE
How to use the relativeTo attribute after V4.0

### ISSUE THREAD

**Issue by HanYuB** [jakubpawlowicz/clean-css#1069]
### Precheck
Drag the css file to nw, but can't process @import css file

### Environment

* clean-css version - 4.2.1
* node.js version - 8.12.0:
* operating system: nwJS v0.15.3

### Configuration options

let CssCleanerCont = new CssCleaner({
  compatibility: 'ie8',
  specialComments : 0,
  format: 'keep-breaks',
  relativeTo: r_path, //css file path
  rebase : true,
  level: {
   2: {
      restructureRules: false,
   }
 }
}).minify(data)

### Input CSS

```css
@charset "utf-8";
@import url("./reset.css");
```

### Actual output CSS

```
@charset "utf-8";
```

### Expected output CSS

```
@charset "utf-8";
reset.css content
```

**Comment by jakubpawlowicz** [comment]
Hello @HanYuB - sorry for not looking at this earlier.

I think what you can do instead of worrying about `relativeTo` attribute is not to use `.minify(data)` but instead

* get rid of `relativeTo` option
* assuming your input source is in `styles.css` file, just use `.minify([r_path + '/styles.css'])`

clean-css will be happier to just read the file for you and rebase URLs accordingly.

Please reopen this issue if needed.
