### ISSUE TITLE
"lineBreak" be configurable

### ISSUE THREAD

**Issue by shenjunru** [jakubpawlowicz/clean-css#238]
Currently, the "lineBreak" depends on the platform.
There is no way to config "lineBreak" from out side.
Please make it configurable.
Thanks.

**Comment by seltix5** [comment]
Hi all.
I did find this problem too. Because I use windows to compile the CSS the output will not be consistent after upload by ftp and manipulation on the Unix server.
Even if I work on windows all my files use Unix LF and they are consistent, the files generated by clean-css are the only exception.
So my only option would be to manually convert the EOL after each compilation or create a php function to do that on the server side and because the upload is by FTP I will need to manually execute this function each time....
In the end I just change the line break value on the clean-css code because none of the after compilation options are interesting nor good.
Thanks

**Comment by jakubpawlowicz** [comment]
@seltix5 we may make it configurable
