### ISSUE TITLE
How to get relativeTo option working with CSS files in different paths

### ISSUE THREAD

**Issue by cristiangrojas** [jakubpawlowicz/clean-css#263]
Imagine the following folder structure for a project inside the static_files folder:

|-- css
    |---- style1.css
    |---- plugins
        |------ plugin1.css
        |------ plugin2.css
        |------ plugin3.css
    |---- whatever_styles
        |------ stylesheet1.css
        |------ stylesheet2.css
        |------ stylesheet3.css
|-- js
    |---- libs
        |------ jquery_plugin
            |-------- jquery_plugin.css
            |-------- jquery_plugin.js
|-- images
    |---- image1.jpg
    |---- image2.jpg
    |---- image3.jpg

As you can see there are many css files distributed on many folders.

Let's suppose that each stylesheet above refers to one of the images in the "images" folder as a background-image for the body or whatever you want.

The path to the image should be different depending of the file where this code is.

Everything ok at this point but... you don't want to have a lot of files so you want to compress them in only one file with clean-css

How should I use the relativeTo option if I want to put my compressed .css file inside a "dist" folder that will be a sibling of the "css", "images" and "js" folders?

I've tried to do it but without good results and I got confused.

Thanks for your support

**Comment by jakubpawlowicz** [comment]
Please reopen if needed.

**Comment by alvarotrigo** [comment]
And what if you have CSS files in multiple locations, lets say, in different bower components for example?
Can you specify multiple relative paths? 

Lets say I have them in :

bower_components/bootstrap/demo.css
bower_components/jqueryui/demo.css
css/myFile.css

**Comment by afinnell** [comment]
Did anyone ever get this working? I am having the EXACT same issue. WRO4J works perfectly. I cannot find a single Gulp or CLI solution that can fix the relative URL's from a subdirectory in which there are multiple sub-directories, each with their own set of CSS files which use relative URL's to themselves. This is frustrating.

**Comment by briceambrosiak** [comment]
Exact same problem than @afinnell here. I'm ending up with absolute path with drive letters when using the `root`option, which is frustrating as is seems to be the only way clean-css sets the full target path.

Any pointers?

**Comment by afinnell** [comment]
I had to give up on this module and use the similarly named module called gulp-clean-css. It worked perfectly.

**Comment by briceambrosiak** [comment]
@afinnell, could you please share your configuration for plugin `gulp-clean-css` ? I'm facing the same issue using `{root: 'src'}` options. 
Thank you!

**Comment by afinnell** [comment]
@bryce I used the relative patting but I'll get you the configuration anyways. Getting power back up after Hurricane.

I did have to split my configuration into two different cleanCSS pipes though. One set of css files had an absolute path in them. For those I didn't use ANY options and it worked perfectly. 

For the set with relative paths I made sure to use relativeTo and target for cleanCSS and base for the gulp.src(). Even without using root I could never get the module this board is we're talking on. As for the other one, gulp-clean-css, as I was saying the trick was not to mix files with relative and ones with absolute. None of the modules could handle that. 

The issue seems to be that the root, target and relativeTo works by accident because POSIX paths are similar to URL paths. Which is why no one thought to check on Windows. The root should produce rebased URL paths based on the root directory of the filesystem. Instead, it makes actual filesystem paths, which works on Linux but only accidently. Using path.join when configuring these modules is the telling sign that they're broke when it comes to pathing. All the options ought to be URL paths.

I'll see about posting my specifics and an example as I spent more time on this then I wanted. if I can save someone else time that'd be great. Sadly, wro4j and lesscss maven plugins work beautifully. I was hoping the gulp world would too.

**Comment by basilmusa** [comment]
A good solution would be to run clean-css twice, once before concatenation just to fix the relative urls problem, and once after concatenation to perform the minification. 

An example is here:

```
var gulp = require('gulp'),
    gutil = require('gulp-util');
var uglify = require('gulp-uglify');
var concat = require('gulp-concat');
var rename = require('gulp-rename');
var cleanCss = require('gulp-clean-css');
gulp.task('concat:tree_ro.css', function() {
  return gulp.src(
        [
                './bootstrap/dist/css/bootstrap.min.css',
                './nlstree/nlstree.css',
                './nlstree/nlsctxmenu.css',
                './styles.css',
                './css/tree_ro.css'
        ],
        {base:"."})
  **.pipe(cleanCss({
        target:"./css",
        keepBreaks:true,
        advanced:false,
        aggressiveMerging:false,
        mediaMerging:false,
        processImport:false,
        shorthandCompacting:false
        }))**
  .pipe(concat('tree_ro_concat.css'))
  **.pipe(cleanCss())**
  .pipe(rename('tree_ro.X.X.X.css'))
  .pipe(gulp.dest('./css'));
});
```

Notice that cleanCss(..) is called twice, the first call disables all minification and only handles the URL problem. The second call performs the real minification without worrying about relative urls since it has been fixed.
