### ISSUE TITLE
Broken CSS should throw an exception

### ISSUE THREAD

**Issue by magnars** [jakubpawlowicz/clean-css#449]
Given broken CSS:

```js
var CleanCSS = require('clean-css');
var source = 'body {color: red';
new CleanCSS().minify(source).styles;
```

clean-css will generate:

```css
body{:[object Object]}
```

It would be great if it instead threw an exception with a line number. :)

**Comment by jakubpawlowicz** [comment]
We definitely should :+1: It in fact we warn in many other cases already: https://github.com/jakubpawlowicz/clean-css/blob/master/test/module-test.js#L96

**Comment by magnars** [comment]
Excellent! :-)

**Comment by jakubpawlowicz** [comment]
@magnars it's solved in master however the current implementation will not give you a line number. It's due to a fact that clean-css counts line numbers when building source maps only. That's for performance reasons, but I'd like to change that at some point: #451.

Hope that's enough for the time being.

**Comment by magnars** [comment]
Thank you! :)
