### ISSUE TITLE
'root' option causing output file to be blank (0 bytes)

### ISSUE THREAD

**Issue by andrewboni** [jakubpawlowicz/clean-css#481]
Running `clean-css` v3.1.4 via Grunt with the `root` option enabled, causes the output file to be empty
```coffeescript
    cssmin:  
      vendor:
        options:
          root: './public'
          target: './public'
          advanced: false
        files:
          'assets/dist/vendor.min.css': [
            "#{libPath}/bootstrap/dist/css/bootstrap.min.css"
        ]
```
```bash
Running "cssmin:vendor" (cssmin) task
Verifying property cssmin.vendor exists in config...OK
Files: public/lib/bootstrap/dist/css/bootstrap.min.css -> assets/dist/vendor.min.css
Options: rebase=false, report="min", sourceMap=false, keepSpecialComments=0, root="./public", target="./public"
Reading public/lib/bootstrap/dist/css/bootstrap.min.css...OK
Writing assets/dist/vendor.min.css...OK
File assets/dist/vendor.min.css created 109.52 kB → 0 B

Done, without errors.
```

Removing the `root` option allows the file to be generated as expected (but without the functionality that `root` is supposed to provide, of course).

Any thoughts on this?

**Comment by jakubpawlowicz** [comment]
@andrewboni No idea. Would you be able to share your setup in a similar manner to https://gist.github.com/MarcBT/2a94d67e36cb634d5c7e or uploaded to Dropbox? You can always mail it to me too via email found in package.json.

**Comment by andrewboni** [comment]
@jakubpawlowicz sure thing. Setup is as follows:
`Gruntfile.coffee`
```coffeescript
module.exports = (grunt) ->
  grunt.initConfig
    cssmin:  
      vendor:
        options:
          root: './public'
          target: './public'
          advanced: false
        files:
          'assets/dist/vendor.min.css': [
            "#{libPath}/bootstrap/dist/css/bootstrap.min.css"
        ]
...
```

`bootstrap.min.css`
Standard bootstrap css file, [found here](https://github.com/twbs/bootstrap/blob/master/dist/css/bootstrap.min.css)

Running `grunt cssmin:vendor` outputs the following:
```bash
Running "cssmin:vendor" (cssmin) task
Verifying property cssmin.vendor exists in config...OK
Files: public/lib/bootstrap/dist/css/bootstrap.min.css -> assets/dist/vendor.min.css
Options: rebase=false, report="min", sourceMap=false, keepSpecialComments=0, root="./public", target="./public"
Reading public/lib/bootstrap/dist/css/bootstrap.min.css...OK
Writing assets/dist/vendor.min.css...OK
File assets/dist/vendor.min.css created 109.52 kB → 0 B

Done, without errors.
```

`vendor.min.css` ends up being a blank file. But, running the task without `root: './public' generates the file as expected. Hope this helps

**Comment by jakubpawlowicz** [comment]
@andrewboni Thanks, I'll take a look later today.

**Comment by jakubpawlowicz** [comment]
@andrewboni I may know what's going on with this setup:

1. adding `root` option sets a root path all passed files should be relative to
2. "#{libPath}/bootstrap/dist/css/bootstrap.min.css" resolves to `public/lib/bootstrap/dist/css/bootstrap.min.css` - see the output above
3. If you set `root: './public'` clean-css will try to resolve the path above as `public/public/lib/bootstrap/dist/css/bootstrap.min.css`, so if it stays empty it will be internally resolved to the current path, i.e. `.`.

Some side notes:

1. If you take a look at https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L33 you'll see clean-css errors are not propagated up to grunt, only exceptions;
2. Actually grunt plugin reads the files but just because it reports file size changes, see https://github.com/gruntjs/grunt-contrib-cssmin/blob/master/tasks/cssmin.js#L42, and it does it _after_ minification takes place.

I will open couple issues in their repo and I'm closing this issue for the time being.
