### ISSUE TITLE
Allow unquoted font names where possible

### ISSUE THREAD

**Issue by jakubpawlowicz** [jakubpawlowicz/clean-css#482]
See https://github.com/jakubpawlowicz/clean-css/issues/282#issuecomment-72422536 comment by @ben-eb

**Comment by kaigon** [comment]
I'm running into this issue regardless of quotes.

```Font: 'Crimson';``` becomes ```Font: #dc143c;```
Double-quotes also yields the same result.

**Comment by jakubpawlowicz** [comment]
@kaigon what version of clean-css do you run? `npm ls` is your friend.

**Comment by kaigon** [comment]
**3.3.6.** However, I'm dumb and just realized I'm using another process to autoprefix / etc, and it's also removing the quotes (which cssmin then converts to hex).

Sorry. Can't believe how long I wasted trying to troubleshoot that.  :\

**Comment by jakubpawlowicz** [comment]
Autoprefixer removing quotes does not sound good...

**Comment by kaigon** [comment]
I was using the PostCSS grunt plugin to load a couple of processors... one was autoprefixer, the other was another (now redundant) css minifier. I just didn't do a good enough job of cleaning up my gruntfile once I switched to cssmin. (and I'm still pretty new to grunt / npm, so that's not doing me any favors).

**Comment by jakubpawlowicz** [comment]
Cool, no problem. I'm glad you sorted it out. :+1:

**Comment by harshbaid** [comment]
I guess fix was not required in this case. Please close this one.
