### ISSUE TITLE
Duplicated @media rules not being removed

### ISSUE THREAD

**Issue by malinky** [jakubpawlowicz/clean-css#508]
I have the critical CSS rules from a number of web pages in one file therefore it contains alot of duplicate styles. When using clean-css all duplicate styles are removed apart from @media rules which are left. Is there way to fix this? For example the below would appear a number of times in the output file.

@media only screen and (min-width:481px) and (max-width:767px){.col-item-full--medium{width:100%}}

**Comment by jakubpawlowicz** [comment]
@malinky in clean-css 3.1 we merge media rules, but duplicates may not be matched, but it depends on your stylesheet. Please feel free to mail me the full file (if possible) so I can take a look.

**Comment by jakubpawlowicz** [comment]
My mail address is in `package.json`.

**Comment by jakubpawlowicz** [comment]
Thanks @malinky for mailing the files. It's not supported right now, but not so hard to add either. Stay tuned for 3.2.

**Comment by rnanwani** [comment]
I am not sure if this is intended, but I was using gulp-minify-css plugin which depends on clean-css. 
After the upgrade to 3.2.4 for clean css, I started facing problems with the media queries. Instead of duplicate media queries being merged, or one of them being removed, both the media queries are getting removed.

The two media queries look like

@media(max-width: 1295px) {
    .extended-content-wrapper {
        width: 1295px;
    }
    .extended-content-wrapper .main-content-col {
        /*float:none!important;*/
    }
    .extended-content-wrapper .side-widget-col {
        /*display:none;*/
    }   
}

@media(max-width: 1295px) {
    .extended-content-wrapper {
        width: 1295px;
    }
    .extended-content-wrapper .main-content-col {
        /*float:none!important;*/
    }
    .extended-content-wrapper .side-widget-col {
        /*display:none;*/
    }   
}


I downgraded gulp-minify-css to use clean-css v3.1.5 and it started working fine again.

**Comment by jakubpawlowicz** [comment]
Can you make sure there's no 3rd same media query in your source file as clean-css removes duplicates now.

Ideally please share your CSS (my email is in package.json).
