### ISSUE TITLE
Root-relative URLs rebase

### ISSUE THREAD

**Issue by speedornothing** [jakubpawlowicz/clean-css#512]
for examples below :
a.css
```
.avatar{
    background:url(/resource/avatar.png)
}
```

now I want to minify a.css to a.min.css. and expect the result :

```
.avatar{background:url(/myProjectName/resource/avatar.png)}
```

how can i make it?

**Comment by jakubpawlowicz** [comment]
There's no built-in way of doing that since there's no way to rewrite one root path to another, as there is no way to relate them.

However I can think of two ways:

1. `new CleanCSS(...).minify(input).styles.replace('url(/resource', 'url(/myProjectName/resource');`
1. Use your web server to do internal rewrite for you (if possible).

Hope that helps.

**Comment by speedornothing** [comment]
thanks for your reply. I find a more secure way using `rework` and `rework-plugin-url`.

```
var result = rework(minifiedCSS).use(reworkPluginUrl(function(url){
    if(url.match(/^\/resource/))
        return '/myProjectName' + url;
    return url;
})).toString();
```

**Comment by jakubpawlowicz** [comment]
Sure, :+1:
