### ISSUE TITLE
Using Clean CSS as a PostCSS plugin

### ISSUE THREAD

**Issue by ScottSmith95** [jakubpawlowicz/clean-css#554]
Is it possible to use clean-css as a PostCSS plugin? It seems that there isn't any documentation about this.

**Comment by jakubpawlowicz** [comment]
There's nothing I'm aware of, however clean-css is a standalone tool so I don't expect there's anything.

**Comment by shinnn** [comment]
@ScottSmith95 Maybe [cssnano](https://github.com/ben-eb/cssnano) meets your requirements. It is a PostCSS-based CSS minifier that can be [used as a PostCSS plugin](https://github.com/ben-eb/cssnano#postcss-nanooptions).

**Comment by jakubpawlowicz** [comment]
@shinnn :+1: I'll close it for now.

**Comment by Saturn2888** [comment]
Based on this benchmark, I'd recommend using Clean-CSS over anything else: https://goalsmashers.github.io/css-minification-benchmark/

Doesn't mean this has to be the end-all for everyone, figured it's good to say why it's important. I was wanting to use Clean-CSS in Webpack since because of React etc, Gulp isn't a reasonable option anymore.

**Comment by jakubpawlowicz** [comment]
Thanks @Saturn2888 - glad it works for you. I always recommend testing against other tools as well to find the best match, which may vary depending on a project.

**Comment by marcobiedermann** [comment]
:+1: for PostCSS plugin. Clean-CSS is the best css minifier out there!

**Comment by raky291** [comment]
Hi everyone, I found this repository [postcss-clean](https://github.com/leodido/postcss-clean), but I don't know if it has bugs, I hope this can be helpful.
