### ISSUE TITLE
[Feat Req.] Add a banner

### ISSUE THREAD

**Issue by KaidenP** [jakubpawlowicz/clean-css#690]
It would be nice to be able to add a banner via cli or api

**Comment by jakubpawlowicz** [comment]
@kkprince1998 could you elaborate what kind of a banner you are thinking about?

**Comment by kkprince1998** [comment]
So once you run this, the output file will have a Banner, Like:
```
/* Copyright ...
 *
 */
```

**Comment by jakubpawlowicz** [comment]
You can always add a banner by yourself and quote it with `/*! ... */` - see https://github.com/jakubpawlowicz/clean-css#how-to-preserve-a-comment-block - hope that helps.

**Comment by kkprince1998** [comment]
I have many css files, and it be nice if I could only have it in one central file.

**Comment by jakubpawlowicz** [comment]
I honestly don't think clean-css is the right place to add a banner. What I'd suggest is doing it in a step after minification by prepending files with copyright info. Clean-css concern is just minifying files.

**Comment by kkprince1998** [comment]
Well, why would uglify support it? It would be the same deal, right? Now I know they are different projects, but in aa wa they are similar.

**Comment by jakubpawlowicz** [comment]
I don't know why UglifyJS supports it. I would argue adding banners it's not in the functionality expected from a minifier.

**Comment by kkprince1998** [comment]
Then perhaps I could make a small patch that does this?

**Comment by unicolored** [comment]
Hi ! I used to add a banner with grunt-contrib-cssmin.
![screenclip](https://cloud.githubusercontent.com/assets/1613177/11105960/abffe4b4-88d2-11e5-8e73-8e203ca263a9.png)


The best interest was that i can update my style.css version based on the package.json version. And since it's for a wordpress theme, it was very useful to enqueue script based on the style.css version via `wp_get_theme('mywordpresstheme')->Version` all automatically.

Now that there's no more banner, i have to update package.json AND my preserved comment block css.
OR i'll look how to generate a css file from Grunt or something like that.

Any idea ?

**Comment by unicolored** [comment]
I find my solution! There's a banner option with the grunt-contrib-less compiler. And the special comment block /*! */ is preserved by grunt-postcss and well understand by wordpress too. That's ok for me!

Clean-css does just it's job now.

**Comment by jakubpawlowicz** [comment]
That's great grunt plugins provide it. 👍
