### ISSUE TITLE
any breaking changes between v2.1.6 and v3.4.6

### ISSUE THREAD

**Issue by adnan-kamili** [jakubpawlowicz/clean-css#691]
We have a very big web application with thousands of css files. Our current  build system uses a very old version of clean-css (v2.1.6) we wish to move to the latest v3.4.6.

Output of minification is not exactly same from both the versions. Is it safe to simply update to the latest version assuming it won't break anything. Our QA is not confident enough.

**Comment by jakubpawlowicz** [comment]
The previous couple version saw many improvements and bugfixes to features already present in 2.1.x. If your current build skips advanced optimizations you should be safe. Otherwise, given your app sice, I would suggest turning off restructuring and everything else should be safe as well.

Hope this helps!

**Comment by adnan-kamili** [comment]
Thanks for the quick response
