### ISSUE TITLE
Add Setting to Move @import to top of minified file

### ISSUE THREAD

**Issue by jlukic** [jakubpawlowicz/clean-css#801]
@import rules [have to precede](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) all other rules in a css file.

Many pipelines that use `clean-css` do some form of concatenation then minification. It would be great if `clean-css` could handle a critical aspect of that process, which is moving `@import` statements to the top of the outputted minified file. 

Typically those building pipelines with concat and minify have to rely on packages like [`gulp-concat-css`](https://github.com/mariocasciaro/gulp-concat-css) to handle moving import statements. Would be great to swap it out and rely on the minifier to correctly move the rules around. :smile:

**Comment by jakubpawlowicz** [comment]
Yup, we could do that when concatenating multiple files.

**Comment by jakubpawlowicz** [comment]
@jlukic @madwizard-thomas I'd like to bring this feature to 4.0.

Quick question - don't you think it should rather inline those imports as they appear at a beginning of a file rather than move them to the beginning of combined file? The former would likely change order of rules and can result in different styling.

**Comment by madwizard-thomas** [comment]
Yes I think you should inline them, minification should never change the effective styles of the stylesheets, which I'm sure can happen if you reorder them.

**Comment by jakubpawlowicz** [comment]
Ok. Do you think it should happen by default or via a switch. I lean towards the former.

**Comment by jakubpawlowicz** [comment]
Here's how I think it should work.

Given:
```css
/* one.css */
@import "path/to/one-import.css";
.one { color: red }
```

```css
/* two.css */
@import "path/to/two-import.css";
.two { color: red }
```

```css
/* three.css */
@import "path/to/three-import.css";
.three { color: red }
```

Then:

* when one does `cat one.css two.css three.css | cleancss` then `@import` rules in `two.css` and `three.css` will be ignored because input comes as one blob as a result of concatenation
* when one does `cleancss one.css two.css three.css` then all `@import` rules will be inlined as three files are explicitly passed to `cleancss`
* when one does `new CleanCSS().minify({ 'one.css': { styles: '...' }, 'two.css': { styles: '...' }, 'three.css': { styles: '...' }})` then all `@import` rules will be inlined too

We should change the examples too so it's more obvious how it works.

Thoughts?

**Comment by madwizard-thomas** [comment]
I think that would be fine. When passing data through stdin it should seem one big file, when specifying filenames they should be parsed as separate CSS files that are then merged. Basically I think cleancss should produce a single file which when included in a HTML file would produce the same results as if the separate source files were included after each other in a HTML file. Merging should not change their meaning. Also when input files from different directories are specified the import should still refer to the correct files (i.e. relative to the respective file they're in).

**Comment by jakubpawlowicz** [comment]
Exactly like that. The last part about relative URLs is already done.

**Comment by jakubpawlowicz** [comment]
Fixed in 426127a. Added test cases & Readme changes. Will land in 4.0.

**Comment by jlukic** [comment]
@jakubpawlowicz The issue with inlining css imports is that it can add remote dependencies to your build tools. 

Imagine for example the `@import` is on google fonts, and you're working on an airplane. You're build would be stuck.

**Comment by jakubpawlowicz** [comment]
@jlukic As we agreed, the default should be just the local ones. It'll ship as a default in 4.0. Otherwise import inlining will follow rules as described [above](https://github.com/jakubpawlowicz/clean-css/issues/801#issuecomment-269232134)
